=== raml-apis/Quizlet/schemas/searchSets-schema.json
{
  "required" : true ,
  "$schema" : "http://json-schema.org/draft-03/schema" ,
  "type" : "object" ,
  "properties" : {
    "total_results" : {
      "type" : "number" ,
      "required" : false
    } ,
    "total_pages" : {
      "type" : "number" ,
      "required" : false
    } ,
    "image_set_count" : {
      "type" : "number" ,
      "required" : false
    } ,
    "page" : {
      "type" : "number" ,
      "required" : false
    } ,
    "sets" : {
      "type" : "array" ,
      "required" : false ,
      "items" : [
        {
          "type" : "object" ,
          "properties" : {
            "id" : {
              "type" : "number" ,
              "required" : false
            } ,
            "url" : {
              "type" : "string" ,
              "required" : false
            } ,
            "title" : {
              "type" : "string" ,
              "required" : false
            } ,
            "created_by" : {
              "type" : "string" ,
              "required" : false
            } ,
            "term_count" : {
              "type" : "number" ,
              "required" : false
            } ,
            "created_date" : {
              "type" : "number" ,
              "required" : false
            } ,
            "modified_date" : {
              "type" : "number" ,
              "required" : false
            } ,
            "has_images" : {
              "type" : "boolean" ,
              "required" : false
            } ,
            "subjects" : {
              "type" : "array" ,
              "required" : false ,
              "items" : [
                {
                  "type" : "string"
                }
              ]
            }
          }
        }
      ]
    }
  }
}

=== raml-apis/Quizlet/examples/searchSets-example.json
{
  "total_results" : 60 ,
  "total_pages" : 2 ,
  "image_set_count" : 35 ,
  "page" : 1 ,
  "sets" : [
    {
      "id" : 6009523 ,
      "url" : "http://quizlet.com/6009523/french-animals-30-flash-cards/" ,
      "title" : "french animals 3.0" ,
      "created_by" : "catchdave" ,
      "term_count" : 13 ,
      "created_date" : 1310497102 ,
      "modified_date" : 1310497363 ,
      "has_images" : true ,
      "subjects" : [
        "french" ,
        "animals"
      ]
    }
  ]
}
