=== raml-apis/Quizlet/schemas/searchUniversal-schema.json
{
  "required" : true ,
  "$schema" : "http://json-schema.org/draft-03/schema" ,
  "type" : "object" ,
  "properties" : {
    "total_results" : {
      "type" : "number" ,
      "required" : false
    } ,
    "total_pages" : {
      "type" : "number" ,
      "required" : false
    } ,
    "page" : {
      "type" : "number" ,
      "required" : false
    } ,
    "items" : {
      "type" : "array" ,
      "required" : false ,
      "items" : [
        {
          "type" : "object" ,
          "properties" : {
            "id" : {
              "type" : "number" ,
              "required" : false
            } ,
            "url" : {
              "type" : "string" ,
              "required" : false
            } ,
            "title" : {
              "type" : "string" ,
              "required" : false
            } ,
            "created_by" : {
              "type" : "string" ,
              "required" : false
            } ,
            "term_count" : {
              "type" : "number" ,
              "required" : false
            } ,
            "created_date" : {
              "type" : "number" ,
              "required" : false
            } ,
            "modified_date" : {
              "type" : "number" ,
              "required" : false
            } ,
            "has_images" : {
              "type" : "boolean" ,
              "required" : false
            } ,
            "subjects" : {
              "type" : "array" ,
              "required" : false ,
              "items" : [
              ]
            } ,
            "visibility" : {
              "type" : "string" ,
              "required" : false
            } ,
            "editable" : {
              "type" : "string" ,
              "required" : false
            } ,
            "has_access" : {
              "type" : "boolean" ,
              "required" : false
            } ,
            "type" : {
              "type" : "string" ,
              "required" : false
            }
          }
        } , {
          "type" : "object" ,
          "properties" : {
            "id" : {
              "type" : "number" ,
              "required" : false
            } ,
            "name" : {
              "type" : "string" ,
              "required" : false
            } ,
            "set_count" : {
              "type" : "string" ,
              "required" : false
            } ,
            "user_count" : {
              "type" : "string" ,
              "required" : false
            } ,
            "created_date" : {
              "type" : "number" ,
              "required" : false
            } ,
            "has_access" : {
              "type" : "boolean" ,
              "required" : false
            } ,
            "has_discussion" : {
              "type" : "boolean" ,
              "required" : false
            } ,
            "description" : {
              "type" : "string" ,
              "required" : false
            } ,
            "admin_only" : {
              "type" : "boolean" ,
              "required" : false
            } ,
            "is_public" : {
              "type" : "boolean" ,
              "required" : false
            } ,
            "has_password" : {
              "type" : "boolean" ,
              "required" : false
            } ,
            "member_add_sets" : {
              "type" : "boolean" ,
              "required" : false
            } ,
            "school" : {
              "type" : "object" ,
              "required" : false ,
              "properties" : {
                "name" : {
                  "type" : "string" ,
                  "required" : false
                } ,
                "id" : {
                  "type" : "number" ,
                  "required" : false
                } ,
                "city" : {
                  "type" : "string" ,
                  "required" : false
                } ,
                "state" : {
                  "type" : "string" ,
                  "required" : false
                } ,
                "country" : {
                  "type" : "string" ,
                  "required" : false
                } ,
                "latitude" : {
                  "type" : "number" ,
                  "required" : false
                } ,
                "longitude" : {
                  "type" : "number" ,
                  "required" : false
                }
              }
            } ,
            "type" : {
              "type" : "string" ,
              "required" : false
            }
          }
        } , {
          "type" : "object" ,
          "properties" : {
            "username" : {
              "type" : "string" ,
              "required" : false
            } ,
            "account_type" : {
              "type" : "string" ,
              "required" : false
            } ,
            "profile_image" : {
              "type" : "string" ,
              "required" : false
            } ,
            "type" : {
              "type" : "string" ,
              "required" : false
            }
          }
        }
      ]
    }
  }
}

=== raml-apis/Quizlet/examples/searchUniversal-example.json
{
  "total_results" : 8027 ,
  "total_pages" : 268 ,
  "page" : 1 ,
  "items" : [
    {
      "id" : 2836910 ,
      "url" : "http://local.quizlet.com/2836910/spanish-iii-h-unidad-2-flash-cards/" ,
      "title" : "Spanish III H unidad 2" ,
      "created_by" : "Scottie814" ,
      "term_count" : 143 ,
      "created_date" : 1285277716 ,
      "modified_date" : 1349320716 ,
      "has_images" : false ,
      "subjects" : [
      ] ,
      "visibility" : "classes" ,
      "editable" : "only_me" ,
      "has_access" : true ,
      "type" : "set"
    } , {
      "id" : 189686 ,
      "name" : "Tampa Spanish Language Class" ,
      "set_count" : "0" ,
      "user_count" : "6" ,
      "created_date" : 1338848121 ,
      "has_access" : false ,
      "has_discussion" : true ,
      "description" : "Spanish Class" ,
      "admin_only" : false ,
      "is_public" : false ,
      "has_password" : false ,
      "member_add_sets" : true ,
      "school" : {
        "name" : "Tampa Spanish Language Class" ,
        "id" : 47677 ,
        "city" : "Tampa" ,
        "state" : "FL" ,
        "country" : "United States" ,
        "latitude" : 0 ,
        "longitude" : 0
      } ,
      "type" : "class"
    } , {
      "username" : "spanish_user" ,
      "account_type" : "free" ,
      "profile_image" : "https://local.quizlet.com/i/animals/19.jpg" ,
      "type" : "user"
    }
  ]
}
